name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Build and push frontend image
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: DockerFile.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/basemodels-front:latest

      # Build and push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: DockerFile.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/basemodels-back:latest
